# Generated by Django 5.2.9 on 2025-12-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_externalsynclog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageLog',
        ),
    ]
