# Generated by Django 5.2.9 on 2025-12-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_delete_messagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('template_name', models.CharField(max_length=100)),
                ('variables', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='core.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'course', 'template_name'], name='whatsapp_ap_student_bbef91_idx'), models.Index(fields=['status'], name='whatsapp_ap_status_0c8489_idx'), models.Index(fields=['created_at'], name='whatsapp_ap_created_acf012_idx')],
            },
        ),
    ]
