# Generated by Django 5.2.9 on 2025-12-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cif', models.CharField(blank=True, default='', max_length=32)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=180)),
                ('dni', models.CharField(blank=True, default='', max_length=32)),
                ('last_medical_exam_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='medical_alerts.company')),
            ],
            options={
                'ordering': ['company__name', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('30_days', '30 days before'), ('15_days', '15 days before'), ('expired', 'Expired')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_to', models.EmailField(max_length=254)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_alert_logs', to='medical_alerts.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_alert_logs', to='medical_alerts.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company'], name='medical_ale_company_c5c43d_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['dni'], name='medical_ale_dni_248ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_medical_exam_date'], name='medical_ale_last_me_f867f7_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalalertlog',
            index=models.Index(fields=['company', 'employee', 'alert_type', 'expiry_date'], name='medical_ale_company_629d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalalertlog',
            index=models.Index(fields=['created_at'], name='medical_ale_created_cd96df_idx'),
        ),
    ]
