# Generated by Django 5.2.9 on 2025-12-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='medical_ale_last_me_f867f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicalalertlog',
            name='medical_ale_company_629d6e_idx',
        ),
        migrations.RenameField(
            model_name='medicalalertlog',
            old_name='expiry_date',
            new_name='target_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_medical_exam_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='next_medical_exam_date',
            field=models.DateField(blank=True, help_text='Fecha prevista del próximo reconocimiento médico', null=True),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['next_medical_exam_date'], name='medical_ale_next_me_19c7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalalertlog',
            index=models.Index(fields=['company', 'employee', 'alert_type', 'target_date'], name='medical_ale_company_b0045d_idx'),
        ),
    ]
