# Generated by Django 5.2.9 on 2025-12-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_alerts', '0002_remove_employee_medical_ale_last_me_f867f7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='medical_ale_next_me_19c7e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicalalertlog',
            name='medical_ale_company_b0045d_idx',
        ),
        migrations.RenameField(
            model_name='medicalalertlog',
            old_name='target_date',
            new_name='reference_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='next_medical_exam_date',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['created_at'], name='medical_ale_created_21c9ab_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalalertlog',
            index=models.Index(fields=['company', 'employee', 'alert_type'], name='medical_ale_company_c763e8_idx'),
        ),
    ]
