# Generated by Django 5.2.9 on 2025-12-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_alerts', '0003_remove_employee_medical_ale_next_me_19c7e6_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='medicalalertlog',
            constraint=models.UniqueConstraint(fields=('company', 'employee', 'alert_type', 'reference_date'), name='uniq_medical_alert_per_employee_date'),
        ),
    ]
